(define fib (lambda (n)
              (cond ((or (= n 0) (= n 1))
                      n)
                    ((< n 0)
                      (* (expt -1 (+ n 1)) (fib (- n))))
                    ((+ (fib (- n 1)) (fib (- n 2)))))))
